### ISSUE TITLE
wir das ne Lan-Party?

### ISSUE THREAD

**Issue by ChrisOKay** [t-karcher/Spiel-zum-Familientag#1]
Oder warum brauchen wir elektronische Unterhaltung beim Familientag?

**Comment by t-karcher** [comment]
Mann bist du schnell! Ich wollte heute abend noch was dazu schreiben. Aber dann schnell hier: Ich dachte weniger an Spielen während des Familientags, sondern an ein kleines "Geschenk" an die Familie als Erinnerung für hinterher. Haaßen-Merchandising sozusagen. :-)
